<html>
    <head>
       <title>Cont de utilizator în rețeaua Med-App</title>
    </head>
    <body>
		<p>
			Bună ziua, </b>

		</p>
		<p>
			Prin acest email, am dori să vă anunțăm că v-a fost creat un cont în cadrul aplicației Med-App. Pentru a vă autentifica, folosiți datele de mai jos.
			<br>
			Email: $user_email$ <br>
			Parolă: $user_password$
	   </p>
	   <p>
			O zi frumoasă!
			<br>
			<br>
			<br>
			<i>
				În cazul în care aveți întrebări, ni le puteți adresa la această adresă de email: <b>medapp.support@gmail.com</b>.
			</i>
	   </p>
   </body>
</html>