<html>
    <head>
       <title>Appointment Confirmation</title>
    </head>
    <body>
		<p>
			Hello, <b> $name$! </b>

		</p>
		<p>
			By this email, we would like to announce you that your doctor's appointment has been confirmed.
			<br>
			You are expected at our office on $date$.
			Looking forward seeing you!
	   </p>
	   <p>
			Have a good day!
			<br>
			<br>
			<br>
			<i>
				In case you have any questions, feel free to email us.
			</i>
	   </p>
   </body>
</html>